<?xml version="1.0" encoding="utf-8"?><Database Name="SalesAccounting" Class="SalesAccountingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\App_Data\SalesAccounting.mdf;Integrated Security=True" SettingsObjectName="HomeWork.Properties.Settings" SettingsPropertyName="SalesAccountingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Goods" Member="Goods">
    <Type Name="Good">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Good_Purchase" Member="Purchases" ThisKey="Id" OtherKey="IdGoods" Type="Purchase" />
    </Type>
  </Table>
  <Table Name="dbo.Purchases" Member="Purchases">
    <Type Name="Purchase">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdGoods" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUnit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DatePurchase" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Purchase_Sale" Member="Sales" ThisKey="Id" OtherKey="IdPurchase" Type="Sale" />
      <Association Name="Good_Purchase" Member="Good" ThisKey="IdGoods" OtherKey="Id" Type="Good" IsForeignKey="true" />
      <Association Name="Unit_Purchase" Member="Unit" ThisKey="IdUnit" OtherKey="Id" Type="Unit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sales" Member="Sales">
    <Type Name="Sale">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateSell" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdSeller" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPurchase" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUnit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Purchase_Sale" Member="Purchase" ThisKey="IdPurchase" OtherKey="Id" Type="Purchase" IsForeignKey="true" />
      <Association Name="Seller_Sale" Member="Seller" ThisKey="IdSeller" OtherKey="Id" Type="Seller" IsForeignKey="true" />
      <Association Name="Unit_Sale" Member="Unit" ThisKey="IdUnit" OtherKey="Id" Type="Unit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sellers" Member="Sellers">
    <Type Name="Seller">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Interest" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Seller_Sale" Member="Sales" ThisKey="Id" OtherKey="IdSeller" Type="Sale" />
    </Type>
  </Table>
  <Table Name="dbo.Units" Member="Units">
    <Type Name="Unit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Short" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Long" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Unit_Purchase" Member="Purchases" ThisKey="Id" OtherKey="IdUnit" Type="Purchase" />
      <Association Name="Unit_Sale" Member="Sales" ThisKey="Id" OtherKey="IdUnit" Type="Sale" />
    </Type>
  </Table>
</Database>